package com.hoaxify.hoaxify.user;

import org.springframework.stereotype.Service;

@Service  // An instance from this class will be generated by Spring
public class UserService {

	UserRepository userRepository;
	//Constructor Injection Instead of using @Autowired- Advantage - If we decide to write unit test for the User Service , we can 
	//create an instance of it class by ourselves. And we can provide a mock version of User Repository through constructor.
	//So we can control external dependencies of this class with this approach.
	// Constructor Injection makes your class more easy to test.
	public UserService(UserRepository userRepository) {
		super();
		this.userRepository = userRepository;
	}
	
	public User save(User user) {
		return userRepository.save(user);
	}
}
